spring.application.name=backend
spring.config.import=optional:file:env.properties
# SERVER CONFIG
server.port=${PORT}
# DB CONFIG
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver=org.postgresql.Driver
# HIBERNATE
spring.jpa.hibernate.ddl-auto=update
# CLOUDINARY
cloudinary.cloud-name=${CLOUDINARY_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}
spring.servlet.multipart.max-file-size=10MB
# JWT
jwt.secret=${JWT_SECRET}
# Resend API (send email)
resend.apikey=${RESEND_API_KEY}
resend.from=${RESEND_FROM_EMAIL}
# CORS
allowed.origins=${ALLOWED_ORIGINS}